[package]
name = "jdt"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
dirs = "5.0.1"
log = "0.4.22"
num-traits = "0.2.19"
once_cell = "1.19.0"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
